### ISSUE TITLE
Invalid Valueset : ValueSet-DD4C-LastingPowerAttorney-Code-1.xml

### ISSUE THREAD

**Issue by clarotech** [nhsconnect/STU3-FHIR-Assets#63]
File ValueSet-DD4C-LastingPowerAttorney-Code-1.xml is invalid in the develop branch.

There are two "<**copyright**>" elements. This is illegal as per the STU3 resource definition for ValueSet

**Comment by clarotech** [comment]
![image](https://user-images.githubusercontent.com/20049400/59494781-cfd2bd00-8e85-11e9-8ef1-544a3b0e336b.png)

**Comment by KatieAnne** [comment]
Thank you for raising this issue. The valueset has now been corrected.
